model_params:
#  model: smp.Unet
  model: SSUnet
  encoder_name: "resnet34"
  in_channels: 4
  encoder_weights: "/logs/proxy/brats/resnet34-tx-200/checkpoints/best.pth"
  classes: &num_classes 1


runner_params:
  input_key: &input_key images
  output_key: logits
  input_target_key: targets


experiment_params:
  experiment: BratsSegment


distributed_params:
  opt_level: O1

args:
  expdir: "src"
  logdir: "/logs/cv_classification"

stages:

  data_params: &data_params
    batch_size: 64
    num_workers: 4

    image_size: &image_size [256, 256]
    train_root_dir: "/data/brats2019/training_preprocess/"
    valid_root_dir: "/data/brats2019/valid_preprocess/"
    train_csv: "./csv/brats_train.csv"
    valid_csv: "./csv/brats_valid.csv"
    data: "WT"

  state_params:
    main_metric: &reduced_metric dice
    minimize_metric: False

  criterion_params:
    criterion: &criterion DiceLoss #BCEWithLogitsLoss

  stage1:

    optimizer_params:
      optimizer: Adam
      lr: 0.0001

    scheduler_params:
      scheduler: OneCycleLRWithWarmup
      num_steps: &num_epochs 25
      lr_range: [0.0005, 0.00001]
      warmup_steps: 5
      momentum_range: [0.85, 0.95]

    state_params:
      num_epochs: *num_epochs

    callbacks_params:
      loss:
        callback: CriterionCallback
      optimizer:
        callback: OptimizerCallback
      dice:
        callback: DiceCallback
      scheduler:
        callback: SchedulerCallback
        reduced_metric: *reduced_metric
      saver:
        callback: CheckpointCallback
        save_n_best: 5