model_params:
  model: proxy_model
  num_classes: 5

runner_params:
  input_key: &input_key images
  output_key: logits
  input_target_key: targets


experiment_params:
  experiment: TemporalMix


distributed_params:
  opt_level: O1

args:
  expdir: "src"
  logdir: "/logs/cv_classification"

share:
  fold: &fold 0
  train_file: &train_file "./csv/5folds/train_0.csv"
  valid_file: &valid_file "./csv/5folds/valid_0.csv"
  image_size: &image_size [224, 224]

stages:

  data_params: &data_params
    batch_size: 128
    num_workers: 4

    train_file: *train_file
    valid_file: *valid_file
    image_size: *image_size

  state_params:
    main_metric: &reduced_metric accuracy01
    minimize_metric: False

  criterion_params:
    criterion: CrossEntropyLoss #FocalLossMultiClass

  optimizer_params:
    optimizer: Adam
    lr: 0.0001
    weight_decay: 0.0001

  stage1:
    state_params:
      num_epochs: &num_epochs 500

    scheduler_params:
#      scheduler: MultiStepLR
#      milestones: [5, 10, 15]
#      gamma: 0.1
      scheduler: OneCycleLRWithWarmup
      num_steps: *num_epochs
      lr_range: [0.0005, 0.000005]
      warmup_steps: 20
      momentum_range: [0.85, 0.95]

    callbacks_params:
      loss:
        callback: CriterionCallback
      optimizer:
        callback: OptimizerCallback
      accuracy:
        callback: AccuracyCallback
        accuracy_args: [1]
      scheduler:
        callback: SchedulerCallback
        reduced_metric: *reduced_metric
      saver:
        callback: CheckpointCallback
        save_n_best: 3
